### ISSUE TITLE
City parameter in "get_city_issues" not working

### ISSUE THREAD

**Issue by joshmwolff** [justindbk/seeclickfixr#1]
When I enter my city as the City parameter in  the following function...

get_city_issues(city="city name"...)

I get results from ALL cities, not just the city whose name I typed in.

**Comment by joshmwolff** [comment]
RESOLVED: The problem was that I was capitalizing the city name. When I used all lowercase to specify city name, the function worked.

**Comment by justindbk** [comment]
great, glad you could resolve!
